- .github/actions/setup/action.yaml
- .github/workflows/test.yaml
- .vscode/settings.json
- tasks/publish.yaml
update uds and zarf versions to latest
remove extraneous cleanup task from ci
add missing --set FLAVOR=${FLAVOR} to the create for release step of release workflow
Fixes #
Relates to #
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix: outdated uds version and missing set value resulting in broken release pipeline

- .github/workflows/test.yaml
...
Fixes #
Relates to #
- [x ] Other (security config, docs update, etc)
> ci: reduce size of runner for test workflow

- values/common-values.yaml
- zarf.yaml
> feat: add BUCKET_PREFIX variable

- .github/workflows/commitlint.yaml
- .github/workflows/pull-request-conditionals.yaml
- .github/workflows/scorecard.yaml
- .github/workflows/tag-and-release.yaml
- .github/workflows/test.yaml
- .yamllint
- bundle/uds-bundle.yaml
- bundle/uds-config.yaml
- common/zarf.yaml
- renovate.json
- tasks.yaml
- tasks/cleanup.yaml
- tasks/lint.yaml
- tasks/publish.yaml
- values/common-values.yaml
- zarf.yaml
Addressing the two related issues. 
1. Breaking renovate changes into package dependencies and support dependencies. 
2. adding yaml linting tasks and github actions 
3. fixing linting errors
Tested in personal mirrored repo for renovate changes, originally in the Renovate Dashboard barely anything was being picked up. 
By using only common renovate.json everything is picked up properly.
...
Fixes #
[Renovate Issue](https://github.com/defenseunicorns/uds-package-gitlab/issues/34)
[Linting Issue](https://github.com/defenseunicorns/uds-package-gitlab/issues/31)
> fix: renovate and linting updates

- .github/workflows/ci-docs-shim.yaml
- .github/workflows/pull-request-conditionals.yaml
- .github/workflows/test.yaml
- included ci shim
Fixes #
Relates to #
> chore: included ci shim

- renovate.json
remove encrypted registry1 renovate creds that are now being pulled in from common config
> chore: remove renovate encrypted creds now pulled from common

- .github/workflows/commitlint.yaml
- .github/workflows/lint.yaml
- .github/workflows/tag-and-release.yaml
- .github/workflows/test.yaml
- tasks.yaml
- tasks/dependencies.yaml
- tasks/publish.yaml
This updates gitlab to use the bundle publish flow added in: https://github.com/defenseunicorns/uds-common/pull/73
Relates to https://github.com/defenseunicorns/uds-software-factory/issues/18
> chore: update to the new bundle publish flow

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
This fixes the workflow rules for linting and testing the repo.
Fixes #N/A
> chore: hotfix workflow run rules

- .github/workflows/commitlint.yaml
- .github/workflows/lint.yaml
- .github/workflows/tag-and-release.yaml
- .github/workflows/test.yaml
- .yamllint
- tasks.yaml
- tasks/dependencies.yaml
- tasks/publish.yaml
This updates this to use the new architecture inputs from uds-common
Fixes #N/A
> chore: update to newer architecture building

- .github/workflows/tag-and-release.yaml
Fixes quotes in tag and release workflow
Fixes #N/A
> chore: fix quotes on release workflow

- renovate.json
Adds a renovate schedule to the repo to avoid paid runner churn
Fixes #N/A
> chore: add a renovate schedule to reduce paid runner churn

- adr/0002-keycloak-integration.md
- keycloak integration ADR.
Fixes https://github.com/defenseunicorns/uds-package-gitlab/issues/54
> docs: keyloak integration ADR

- .github/workflows/ci-docs-shim.yaml
> chore: release v16.10.1-uds.0

- src/dev-secrets/postgres-secret.yaml
- src/dev-secrets/zarf.yaml
This cleans up dev secrets to remove postgres references.
Fixes #N/A
> chore: cleanup dev secrets to remove postgres refs

- values/common-values.yaml
This hotfixes some issues with uds-prod-infrastructure: https://github.com/defenseunicorns/uds-prod-infrastructure/actions/runs/9181909401/job/25249770738
Fixes #N/A
> chore: address prod issues with gitlab

- chart/templates/uds-package.yaml
https://github.com/defenseunicorns/uds-package-gitlab/issues/141
> fix: add missing exporter netpols

- .github/workflows/tag-and-release.yaml
- .github/workflows/test.yaml
- tasks/test.yaml
Change to docker container to run playwright tests to help with cache issues.
Fixes #N/A
> chore: change playwright to a docker container

- common/zarf.yaml
- values/registry1-values.yaml
- values/upstream-values.yaml
- zarf.yaml
update chart to correct version and swap ubi images with gitlab-base
> fix: update chart and swap images to fix update

- .github/workflows/ci-docs-shim.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/lint.yaml
- README.md
- docs/configuration.md
Streamline README and add workflow permissions
Fixes #N/A
> chore: streamline README and add workflow permissions

- .github/workflows/commitlint.yaml
> chore: update commitlint.yaml permissions

- README.md
> chore: fix S2->S3 in README.md

- releaser.yaml
> chore: update releaser.yaml
